### ISSUE TITLE
抓取过程中会中断，该如何处理呀？

### ISSUE THREAD

**Issue by ShawnLinLoveLife** [xjkj123/Lianjia#4]
100%|███████████████████████████████████████| 2460/2460 [08:58<00:00,  4.88it/s]
100%|███████████████████████████████████████| 2580/2580 [09:10<00:00,  4.39it/s]
 57%|██████████████████████▍                | 2139/3721 [07:40<05:45,  4.58it/s]100%|███████████████████████████████████████| 3721/3721 [13:28<00:00,  4.82it/s]
  7%|██▍                                 | 1504/22010 [05:22<1:12:00,  4.75it/s]100%|███████████████████████████████████| 22010/22010 [1:22:34<00:00,  4.49it/s]
  0%|                                                  | 0/8116 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test.py", line 7, in <module>
    lj.GetCompleteHousingInfo(city)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Lianjia/lianjia.py", line 505, in GetCompleteHousingInfo
    ret = Lianjia(city).GetHousingInfo(x[0], x[1])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Lianjia/lianjia.py", line 386, in GetHousingInfo
    for x in house_json['data']['ershoufang_info']['list']:
TypeError: 'NoneType' object is not subscriptable

**Comment by xjkj123** [comment]
已解决,已上传代码
